domain:
  url:  ${domain:https://test.wenzhuo4657.org}
  home:  ${domain.url}

github:
  client-id:  ${GITHUB_CLIENT_ID:Ov23liun5XKbVZU2iExz}
  client-secret:  ${GITHUB_CLIENT_SECRET:8432da91561cf6cd00368e4bbbe495a160786690}
  redirect-uri: ${domain.url}/api/oauth/callback/github

email:
  enable: true
  config:
    from: wenzhuo4657@gmail.com
    to: wenzhuo4657@gmail.com
    password: ${GMAIL_PASSWORD}


